/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kelompok 3.
 */

import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class topuphyugo extends javax.swing.JFrame {

    /**
     * Creates new form klmpok3_UTS
     */
    
    private JLabel imageLabel;
    private JLabel successTextLabel;
    
    private void groupButton(){
       ButtonGroup bg1=new ButtonGroup();
       bg1.add(jRadioButton1);
       bg1.add(jRadioButton2);
       bg1.add(jRadioButton3);
       bg1.add(jRadioButton4);
    }
    public topuphyugo() {
        initComponents();
        groupButton();
        // nampilin bahasa pertama saat dibuka
        jTextField3.setText("Indonesia");
        
        // jaga-jaga kalo nanti scrollbar error tibatba
        jScrollBar1.setMinimum(0);
        jScrollBar1.setMaximum(10); //bisa juga set maximum, tapi biar dinamis aja
        jScrollBar1.setVisibleAmount(1);
        
        // Menonaktifkan tab kedua, ketiga, dan keempat saat aplikasi dimulai
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        resend = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        epic = new javax.swing.JCheckBox();
        legend = new javax.swing.JCheckBox();
        mythic = new javax.swing.JCheckBox();
        mythichonor = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnAksi = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jgmbr = new javax.swing.JPanel();
        cetaklaporan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField3 = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        resend.setText("Resend Order");
        resend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resendActionPerformed(evt);
            }
        });
        jPopupMenu1.add(resend);

        delete.setText("Delete Order");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(delete);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(63, 84, 156));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SIGN IN HYUGOSTORE");
        jLabel15.setOpaque(true);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 270, 40));

        jLabel8.setBackground(new java.awt.Color(63, 84, 156));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Username :");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 30));

        email.setToolTipText("masukkan");
        email.setName(""); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 175, 30));
        email.getAccessibleContext().setAccessibleName("");
        email.getAccessibleContext().setAccessibleDescription("");

        jLabel10.setBackground(new java.awt.Color(63, 84, 156));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password  :");
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 30));

        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 30));

        nama.setToolTipText("masukkan");
        nama.setName(""); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 175, 30));

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"}));
        jSpinner1.setToolTipText("");
        jSpinner1.setName(""); // NOI18N
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 80, 30));

        jLabel17.setBackground(new java.awt.Color(63, 84, 156));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nama Lengkap :");
        jLabel17.setOpaque(true);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 120, 30));

        jLabel18.setBackground(new java.awt.Color(63, 84, 156));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tanggal Lahir :");
        jLabel18.setOpaque(true);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, 30));

        jLabel19.setBackground(new java.awt.Color(63, 84, 156));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Email :");
        jLabel19.setOpaque(true);
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        username.setToolTipText("masukkan");
        username.setName(""); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 175, 30));

        password.setToolTipText("masukkan");
        password.setName(""); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 175, 30));

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"}));
        jSpinner2.setToolTipText("");
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 120, 30));

        jSpinner3.setModel(new javax.swing.SpinnerListModel(new String[] {"1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "Sekarang"}));
        jPanel2.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 70, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brody.jpeg"))); // NOI18N
        jLabel16.setText("l");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -60, -1, -1));

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Region");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setBackground(new java.awt.Color(63, 84, 156));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pilih Paket Diamond");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));

        jPanel3.setBackground(new java.awt.Color(63, 84, 156));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setName(""); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIAMOND");

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10 Diamond", "50 Diamond", "150 Diamond", "270 Diamond", "560 Diamond", "1020 Diamond", "5000 Diamond" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel4.setBackground(new java.awt.Color(63, 84, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JOKI");

        epic.setForeground(new java.awt.Color(255, 255, 255));
        epic.setText("Epic - Legend");
        epic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epicActionPerformed(evt);
            }
        });

        legend.setForeground(new java.awt.Color(255, 255, 255));
        legend.setText("Legend - Mythic");

        mythic.setForeground(new java.awt.Color(255, 255, 255));
        mythic.setText("Mythic - Mythic Honor");
        mythic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mythicActionPerformed(evt);
            }
        });

        mythichonor.setForeground(new java.awt.Color(255, 255, 255));
        mythichonor.setText("Mythic honor - Immortal");
        mythichonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mythichonorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(epic, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(legend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mythic, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mythichonor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(epic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mythic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mythichonor)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));
        jPanel4.getAccessibleContext().setAccessibleName("JOKI");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "Philipina", "Malaysia", "Brunnei Darussalam", "Myanmar", "Thailand", "Korea Selatan", "Amerika Serikat", "Jepang" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Akun + Server : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 159, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 102, -1));

        jLabel6.setBackground(new java.awt.Color(63, 84, 156));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Top Up Mobile Legends");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 290, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Metode Pembayaran ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(63, 84, 156));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Dana");
        jRadioButton1.setOpaque(true);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 91, -1));

        jRadioButton2.setBackground(new java.awt.Color(63, 84, 156));
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("ShopePay");
        jRadioButton2.setOpaque(true);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 120, -1));

        jRadioButton3.setBackground(new java.awt.Color(63, 84, 156));
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Via Bank  ");
        jRadioButton3.setOpaque(true);
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 110, -1));

        jRadioButton4.setBackground(new java.awt.Color(63, 84, 156));
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("MiniMarket");
        jRadioButton4.setOpaque(true);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 97, -1));

        btnAksi.setText("Buy");
        btnAksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnAksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 103, -1));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 95, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prsha.jpeg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 730, 1310));

        jTabbedPane1.addTab("Top Up", jPanel1);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(63, 84, 156));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Riwayat Top Up ");
        jLabel14.setOpaque(true);
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 275, 106));

        jButton1.setBackground(new java.awt.Color(63, 84, 156));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lainnya");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, 30));

        jgmbr.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jgmbrLayout = new javax.swing.GroupLayout(jgmbr);
        jgmbr.setLayout(jgmbrLayout);
        jgmbrLayout.setHorizontalGroup(
            jgmbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jgmbrLayout.setVerticalGroup(
            jgmbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel6.add(jgmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 200));

        cetaklaporan.setText("Cetak Laporan");
        cetaklaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetaklaporanActionPerformed(evt);
            }
        });
        jPanel6.add(cetaklaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brody.jpeg"))); // NOI18N
        jButton2.setText("jButton2");
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jTabbedPane1.addTab("Riwayat Transaksi ", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pengaturan Aplikasi : ");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(63, 84, 156));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Isi apa aja");
        jPanel7.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 161, -1));

        jCheckBox2.setBackground(new java.awt.Color(63, 84, 156));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Donat enak kayanya");
        jPanel7.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bahasa : ");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jScrollBar1.setMaximum(10);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.setVisibleAmount(1);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        jPanel7.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 362, 30));

        jTextField3.setEditable(false);
        jTextField3.setColumns(20);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 149, 30));

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel7.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 110, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frdrin.jpeg"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 1310));

        jTabbedPane1.addTab("Pengaturan", jPanel7);

        jMenu1.setText("Pusat Bantuan");

        jMenuItem1.setText("Bantuan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Saran");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void epicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epicActionPerformed

    private void mythicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mythicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mythicActionPerformed

    private void mythichonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mythichonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mythichonorActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiActionPerformed
    // Ambil data transaksi
    String region = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";
    String diamond = jList1.getSelectedValue() != null ? jList1.getSelectedValue() : "";
    String id = jTextField1.getText();
    String server = jTextField2.getText();
    String metodePembayaran = "";

    if (jRadioButton1.isSelected()) metodePembayaran = "Dana";
    else if (jRadioButton2.isSelected()) metodePembayaran = "ShopeePay";
    else if (jRadioButton3.isSelected()) metodePembayaran = "Via Bank";
    else if (jRadioButton4.isSelected()) metodePembayaran = "MiniMarket";

    // Ambil pilihan rank yang dipilih
    String rank = "";
    if (epic.isSelected()) rank = "Epic - Legend";
    else if (legend.isSelected()) rank = "Legend - Mythic";
    else if (mythic.isSelected()) rank = "Mythic - Mythic Honor";
    else if (mythichonor.isSelected()) rank = "Mythic Honor - Immortal";

    // Pastikan semua data sudah diisi sebelum lanjut
    if (region.isEmpty() || diamond.isEmpty() || id.isEmpty() || server.isEmpty() || metodePembayaran.isEmpty() ) {
        JOptionPane.showMessageDialog(null, "Harap isi semua informasi sebelum menyetujui transaksi!");
        return;
    }

    // Format data transaksi dengan rank yang dipilih
    String transaksi = "Transaksi Joki Mobile Legends\n" +
                       "ID: " + id + "\n" +
                       "Server: " + server + "\n" +
                       "Region: " + region + "\n" +
                       "Diamond: " + diamond + "\n" +
                       "Joki Rank: " + rank + "\n" +
                       "Metode Pembayaran: " + metodePembayaran + "\n";

    // Masukkan teks ke jTextArea1
    jTextArea1.append(transaksi + "\n\n");
    
    simpanTransaksi(id, server, region, diamond, rank, metodePembayaran);
   
    //teks sukses
    successTextLabel = new JLabel("Yeayyyy Pesanan berhasil!");
    successTextLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 17));
    successTextLabel.setBounds(10, 10, 300, 340);
    
    
    ImageIcon imageIcon = new ImageIcon(getClass().getResource("/yay.gif"));
    JLabel imageLabel = new JLabel(imageIcon); // Menambahkan gambar ke JLabel

    // Menambahkan gambar pada panel Riwayat Transaksi
    imageLabel.setBounds(-5, -23, imageIcon.getIconWidth(), imageIcon.getIconHeight());
    jgmbr.add(successTextLabel);
    jgmbr.add(imageLabel);
    jgmbr.setLayout(null); // Agar kita bisa bebas tempatkan komponen
    
    jgmbr.repaint();

    
    // Aktifkan tab Riwayat Transaksi jika belum aktif
    jTabbedPane1.setEnabledAt(2, true);

    // Pindah ke tab Riwayat Transaksi
    jTabbedPane1.setSelectedIndex(2); 
    }//GEN-LAST:event_btnAksiActionPerformed
    
    private void simpanTransaksi(String id, String server, String region, String diamond, String rank, String metodePembayaran) {
    try {
        Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/topupml", "topupml", "123");

        String sql = "INSERT INTO TOPUPML (ID, SERVER, REGION, DIAMOND, RANK, METODE_PEMBAYARAN) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, id);
        pst.setString(2, server);
        pst.setString(3, region);
        pst.setString(4, diamond);
        pst.setString(5, rank);
        pst.setString(6, metodePembayaran);

        pst.executeUpdate();
        conn.close();
        
        System.out.println("Transaksi berhasil disimpan!");

    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    JFrame bantuanFrame = new JFrame("Bantuan");
    bantuanFrame.setSize(500, 400);
    bantuanFrame.setLocationRelativeTo(null);
    bantuanFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    bantuanFrame.setLayout(new BorderLayout());

    JButton pilihFileButton = new JButton("Pilih File");
    bantuanFrame.add(pilihFileButton, BorderLayout.NORTH);

    JTextArea isiFileArea = new JTextArea();
    isiFileArea.setEditable(false);
    isiFileArea.setLineWrap(true);
    isiFileArea.setWrapStyleWord(true);

    JScrollPane scroll = new JScrollPane(isiFileArea);
    bantuanFrame.add(scroll, BorderLayout.CENTER);
    

    pilihFileButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JFileChooser fileChooser = new JFileChooser();
            int pilih = fileChooser.showOpenDialog(bantuanFrame);
            if (pilih == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                String namaFile = file.getName(); // Ambil nama file aja
                isiFileArea.setText(namaFile); // Tampilkan di textarea
            }
        }
    });

    bantuanFrame.setVisible(true);    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                         
    // Buat popup menu
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:                                                                            
    int pilihan = JOptionPane.showConfirmDialog(null, 
        "Apakah Anda yakin ingin membatalkan transaksi?", "Konfirmasi Pembatalan", 
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (pilihan == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null, "Transaksi telah dibatalkan. Semua pilihan di-reset.");

        // Reset semua input
        jComboBox1.setSelectedIndex(-1);
        jList1.clearSelection();
        jTextField1.setText("");
        jTextField2.setText("");

        // Kosongkan pilihan metode pembayaran
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);

        // Kosongkan semua checkbox
        epic.setSelected(false);
        legend.setSelected(false);
        mythic.setSelected(false);
        mythichonor.setSelected(false);

        // Pastikan pengguna tetap di halaman Top Up
        jTabbedPane1.setSelectedIndex(1);
    } else {
        JOptionPane.showMessageDialog(null, "Pembatalan transaksi dibatalkan.");
    }
    }//GEN-LAST:event_cancelActionPerformed

    private void resendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendActionPerformed
        // TODO add your handling code here:                                                                            
    int pilihan = JOptionPane.showConfirmDialog(null, 
        "Apakah Anda yakin ingin mengirim ulang pesanan ini?", "Konfirmasi Resend Order", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (pilihan == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null, "Pesanan sedang dikirim ulang...");
        
        // Ambil data transaksi yang sebelumnya dibuat
        String region = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";
        String diamond = jList1.getSelectedValue() != null ? jList1.getSelectedValue() : "";
        String id = jTextField1.getText();
        String server = jTextField2.getText();
        String metodePembayaran = "";

        if (jRadioButton1.isSelected()) metodePembayaran = "Dana";
        else if (jRadioButton2.isSelected()) metodePembayaran = "ShopeePay";
        else if (jRadioButton3.isSelected()) metodePembayaran = "Via Bank";
        else if (jRadioButton4.isSelected()) metodePembayaran = "MiniMarket";
        
        // Ambil pilihan rank yang dipilih
        String rank = "";
        if (epic.isSelected()) rank = "Epic - Legend";
        else if (legend.isSelected()) rank = "Legend - Mythic";
        else if (mythic.isSelected()) rank = "Mythic - Mythic Honor";
        else if (mythichonor.isSelected()) rank = "Mythic Honor - Immortal";

        // Pastikan semua data telah diisi sebelum resend order
        if (region.isEmpty() || diamond.isEmpty() || id.isEmpty() || server.isEmpty() || metodePembayaran.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi semua informasi sebelum mengirim ulang transaksi!");
            return;
        }

        // Format ulang data transaksi dan tambahkan ke Riwayat Transaksi
        String transaksi = "Pesanan Dikirim Ulang!\n" +
                       "ID: " + id + "\n" +
                       "Server: " + server + "\n" +
                       "Region: " + region + "\n" +
                       "Diamond: " + diamond + "\n" +
                       "Joki Rank: " + rank + "\n" +
                       "Metode Pembayaran: " + metodePembayaran + "\n";

        jTextArea1.append(transaksi + "\n\n");
        
        if (imageLabel != null) jgmbr.remove(imageLabel);
        if (successTextLabel != null) jgmbr.remove(successTextLabel);
            //teks sukses
        successTextLabel = new JLabel("Pesanan berhasil di resend");
        successTextLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 17));
        successTextLabel.setBounds(10, 10, 300, 340);
        
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/yay.gif"));
        imageLabel = new JLabel(imageIcon);
        imageLabel.setBounds(-5, -23, imageIcon.getIconWidth(), imageIcon.getIconHeight());

        jgmbr.add(successTextLabel);
        jgmbr.add(imageLabel);
        jgmbr.repaint();

        jTabbedPane1.setSelectedIndex(2);
    } else {
        JOptionPane.showMessageDialog(null, "Pengiriman ulang dibatalkan.");
    }
    }//GEN-LAST:event_resendActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:                                      
    int pilihan = JOptionPane.showConfirmDialog(null, 
        "Apakah Anda yakin ingin menghapus transaksi ini?", "Konfirmasi Penghapusan", 
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (pilihan == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null, "Transaksi berhasil dihapus.");
        
        // Kosongkan teks transaksi di JTextArea
        jTextArea1.setText("");
         // Hapus gambar jika ada
        if (imageLabel != null) {
        jgmbr.remove(imageLabel);
        imageLabel = null;
        }
        if (successTextLabel != null) {
            jgmbr.remove(successTextLabel);
            successTextLabel = null;
        }
        jgmbr.repaint();
        
        
        System.out.println("Transaksi telah dihapus.");
    } else {
        JOptionPane.showMessageDialog(null, "Penghapusan transaksi dibatalkan.");
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
            JPopupMenu menu = new JPopupMenu();

            JMenuItem resendItem = new JMenuItem("Resend");
            JMenuItem deleteItem = new JMenuItem("Delete");

            resendItem.addActionListener(e -> resendActionPerformed(null));
            deleteItem.addActionListener(e -> deleteActionPerformed(null));

            menu.add(resendItem);
            menu.add(deleteItem);

            // Tampilkan popup di bawah tombol
            Component source = (Component) evt.getSource();
            menu.show(source, 0, source.getHeight());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        String[] languages = {
            "Indonesia", "English", "Jepang", "China", "Korea",
            "Spanyol", "Prancis", "Jerman", "Arab", "Rusia"
        };
        int index = jScrollBar1.getValue();
        if (index >= 0 && index < languages.length) {
            jTextField3.setText(languages[index]);
        }
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String usernameText = username.getText();
        String passwordText = password.getText();
        String namaText = nama.getText();
        String emailText = email.getText();
        

        if (!usernameText.isEmpty() && !passwordText.isEmpty() && !namaText.isEmpty() && !emailText.isEmpty()) {
            jTabbedPane1.setEnabledAt(1, true);
            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setEnabledAt(3, true);
            JOptionPane.showMessageDialog(null, "Login berhasil! Selamat Datang " + usernameText + " di HYUGOSTORE ");
            
            jTabbedPane1.setEnabledAt(1, true);
            // Pindah ke tab Riwayat Transaksi
            jTabbedPane1.setSelectedIndex(1);

        } else {
            JOptionPane.showMessageDialog(null, "Harap masukkan semua data (Username, Password, Nama, dan Email) sebelum lanjut!");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    JFrame saranFrame = new JFrame("Saran");
    saranFrame.setSize(500, 400);
    saranFrame.setLocationRelativeTo(null);
    saranFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    saranFrame.setLayout(new BorderLayout());

    JTextArea saranArea = new JTextArea();
    saranArea.setLineWrap(true);
    saranArea.setWrapStyleWord(true);

    JScrollPane saranScroll = new JScrollPane(saranArea);
    saranFrame.add(saranScroll, BorderLayout.CENTER);

    JButton kirimButton = new JButton("Kirim");
    saranFrame.add(kirimButton, BorderLayout.SOUTH);

 
    kirimButton.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String isiSaran = saranArea.getText();
        if (!isiSaran.isEmpty()) {
            JOptionPane.showMessageDialog(saranFrame, "Saran telah dikirim:\n" + isiSaran);
            saranArea.setText(""); // kosongkan setelah kirim
        } else {
            JOptionPane.showMessageDialog(saranFrame, "Silakan isi saran terlebih dahulu.");
        }
    }
});

saranFrame.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    jTabbedPane1.setSelectedIndex(0);
    jTabbedPane1.setEnabledAt(1, false); 
    jTabbedPane1.setEnabledAt(2, false); 
    jTabbedPane1.setEnabledAt(3, false);
    username.setText("");
    password.setText("");
    nama.setText("");
    email.setText("");
    JOptionPane.showMessageDialog(null, "Berhasil logout!");
    }//GEN-LAST:event_logoutActionPerformed

    private void cetaklaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetaklaporanActionPerformed
       try {
        // 1. Koneksi ke database
        Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/topupml", "topupml", "123");

        // 2. Compile file jrxml yang ada di folder "report"
        JasperReport report = JasperCompileManager.compileReport(
            getClass().getResourceAsStream("/report/transaksiReport.jrxml")
        );

        // 3. Isi laporan tanpa parameter (null), ambil dari database
        JasperPrint print = JasperFillManager.fillReport(report, null, conn);

        // 4. Tampilkan laporan
        JasperViewer.viewReport(print, false);
        
        // Ekspor ke PDF
        JasperExportManager.exportReportToPdfFile(print, "laporan.pdf");


    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak laporan: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_cetaklaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(topuphyugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(topuphyugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(topuphyugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(topuphyugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new topuphyugo().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksi;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cetaklaporan;
    private javax.swing.JMenuItem delete;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBox epic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel jgmbr;
    private javax.swing.JCheckBox legend;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JCheckBox mythic;
    private javax.swing.JCheckBox mythichonor;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField password;
    private javax.swing.JMenuItem resend;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
